version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=sqlite:///timewebsite.db
    volumes:
      - .:/usr/src/app
    command: python run.py
